# Generated by Django 5.2.8 on 2025-11-18 03:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id_negocio', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('restaurante', 'Restaurante'), ('minorista', 'Minorista'), ('servicio', 'Servicio'), ('hosteleria', 'Hostelería'), ('creativo', 'Creativo'), ('otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('horario_apertura', models.TimeField(blank=True, null=True)),
                ('horario_cierre', models.TimeField(blank=True, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('id_usuario', models.BigIntegerField()),
                ('tenant_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'negocios',
                'ordering': ['-creado_en'],
            },
        ),
    ]
