# Generated by Django 5.2.8 on 2025-11-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='logo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='sitio_web',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
